Vagrant.configure("2") do |config|

  # Configuration globale pour toute les VM
  config.vm.box = "debian/bookworm64"

  # VM 1 = SRV-WEB
  config.vm.define "web" do |web|
    # Hostname du serveur
    web.vm.hostname = "srv-web"
    # Configuration IP sur réseau privé VirtualBox
    web.vm.network "private_network", ip: "10.0.0.10"
    # Mappage de ports 80 -> 8080
    web.vm.network "forwarded_port", guest: 80, host: 8080
    # Mappage d'un dossier partagé
    web.vm.synced_folder "./www", "/var/www/html"
    # On appelle un script externe
    web.vm.provision "shell", path: "scripts/web.sh"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "SRV-WEB"
      vb.memory = "1024"
      vb.cpus = 1
    end

  end

  # VM 2 = SRV-DB
  config.vm.define "db" do |db|
    db.vm.hostname = "srv-db"
    db.vm.network "private_network", ip: "10.0.0.11"
    db.vm.provision "shell", path: "scripts/db.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "SRV-DB"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end