Vagrant.configure("2") do |config|

  # On défini la box pour la VM
  config.vm.box = "debian/bookworm64"

  # On défini le hostname de la machine
  config.vm.hostname = "srv-web"

  # Nouveauté 1 : Mappage de ports
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip:"192.168.56.10"

  # Nouveauté 2 : Dossier partagé
  config.vm.synced_folder "./www", "/var/www/html"
  
  # Nouveauté 3 : Le provisionning shell
  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y
    apt install apache2 -y
    # On s'assure qu'Apache aura les droits sur le dossier html
    chown -R www-data:www-data /var/www/html
  SHELL

  # Configuration de la VM Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "VM-WEB"
    vb.memory = "2048"
    vb.cpus = 2
  end
end