--- # Début du playbook
- name: "Configuration de base et sécurisation du serveur" # Nom du projet
  hosts: all # S'applique à toutes les machines
  become: true # Exécuter toutes les tâches en tant que 'root'

  tasks: # Liste des tâches à effectuer dans l'ordre

    # --- PARTIE 1 : MISE A JOUR DU SYSTEME ---
    - name: "Mise a jour complète du système (apt update & upgrade)" # Nom de la tâche
      apt:
        update_cache: yes # Fait un apt update
        upgrade: dist # Fait un apt dist-upgrade (mise à jour complète)
        cache_valid_time: 3600 # Ne refait l'update que si le dernier date de + 1H

    # --- PARTIE 2 : INSTALLATION DU SERVEUR WEB ---
    - name: "Installation du serveur apache2"
      apt:
        name: apache2
        state: present # S'assure que le packet est installé

    - name: "Demarrage de apache2"
      service:
        name: apache2
        state: started # lance le service
        enabled: true # L'active au démarrage du système

    # --- PARTIE 3 : SECURISATION AVEC UFW ---
    - name: "Installation du packet UFW (Firewall)"
      apt:
        name: ufw
        state: present

    - name: "Autoriser SSH (Port 22) - CRITIQUE pour Vagrant"
      ufw:
        rule: allow # Autoriser
        port: '22' 
        proto: tcp

    - name: "Autoriser HTTP (Port 80)"
      ufw:
        rule: allow # Autoriser
        port: '80' 
        proto: tcp

    - name: "Activer le Firewall et bloquer tout le reste par defaut"
      ufw:
        state: enabled
        policy: deny # Politique par defaut : tout refuser sauf nos règles
        direction: incoming # Pour le tafic entrant

    # --- PARTIE 4 : CONTENU DE TEST ---
    - name: "Création de la page d'accueil"
      copy:
        content: "<h1 style='color: red;'>Ma super page web avec Ansible</h1>"
        dest: /var/www/html/index.html

