# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  #On défini notre BOX
  config.vm.box = "ubuntu/jammy64"

  #On défini le hostname de la machine
  config.vm.hostname = "vm-decouverte"

  #On défini le réseau privé de l'hôte
  #Cela permet d'éviter d'accéder à la VM via le NAT
  config.vm.network "private_network", ip:"192.168.56.10"

  #On défini les ressources alloué à la VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "VM-DECOUVERTE"
    vb.memory = "1024"
    vb.cpus = 1
  end
end
